### ISSUE TITLE
Mark mod as unstable

### ISSUE THREAD

**Issue by Computerdores** [Shaosil/LethalCompanyMods-GeneralImprovements#155] opened 2024-04-21 16:58 UTC
I would suggest you add warning to the Thunderstore page that makes it very obvious that this mod is unstable, because we landed just three times and had all of the following issues which were gone after removing this mod:
- Lag Spikes
- Suits were outside the ship
- Items were sometimes teleported outside to the same spot as the suits
- Lights were desynced and other desyncs happend as well (items, furniture, etc.)
- when joining the lobby all items that players had picked up were still on the ground but not able to picked up
- Steam overlay was broken

**Comment by Computerdores** [comment] 2024-04-21 17:09
Oh and sometimes the loot in the ship would stay on the moon but be teleported to the ship once in orbit, but I am not whether that was from this mod

**Comment by Shaosil** [comment] 2024-04-21 18:37
So, a few things:

1) First, most of those issues are very likely caused by a mod _conflict_, not my mod. Thousands of people use my mod daily (myself and my friends included) and have never seen any of the behavior you described.

2) I know my mod definitely doesn't touch suits, lights, or anything Steam related in any way.

3) Lag spike sources are very difficult to track down, but my mod does quite a bit of optimization even when you enable some of the heavier configs. UseBetterMonitors = true can have a slight effect but it wouldn't be significant in most cases.

4) Loot staying on the moon during takeoff and teleporting to the ship afterwards has always been a bug in vanilla.

5) Finally, mod conflicts can sometimes be very sensitive. Were there errors in the log? How many and which mods were you using? Do you have a profile code? Etc.

I'm going to close this as unplanned because I'm not aware of any solid evidence that my mod is unstable unless paired with other conflicting mods, which, it goes without saying, is always a risk when using mods in any game.

**Closed by Shaosil** 2024-04-21 18:37 UTC
