### ISSUE TITLE
[1.0.17] Softlock on Orbit

### ISSUE THREAD

**Issue by SrMoroxide** [Shaosil/LethalCompanyMods-GeneralImprovements#24] opened 2024-01-13 22:59 UTC
When downloading the latest version, when you go into orbit when you leave the moon, the day does not pass.
The scrap achieved and experience boxes are shown, but the one indicating the remaining days of the deadline is not.

I am using TheMostLethalCompany modpack and added this mod, there may be some incompatibility like Corporate_Restructure by Jamil.

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/152836693/0da68201-1881-4a2a-b0ff-0886cfed6484)

**Comment by Shaosil** [comment] 2024-01-13 23:10
Yeah I think this is a duplicate of #23, I'll be looking into this as soon as I can

**Comment by Shaosil** [comment] 2024-01-14 03:40
Fixed in v1.0.18, which should be live shortly

**Closed by Shaosil** 2024-01-14 03:40 UTC
