### ISSUE TITLE
Adding ToggleableFancyLamp behavior to FancyLamp prefab.

### ISSUE THREAD

**Issue by apeng0907** [Shaosil/LethalCompanyMods-GeneralImprovements#130] opened 2024-02-23 06:50 UTC
[Info   :GeneralImprovements] Adding ToggleableFancyLamp behavior to FancyLamp prefab.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LethalThings.Patches.PowerOutletStun.GameNetworkManager_Start (On.GameNetworkManager+orig_Start orig, GameNetworkManager self) (at O:/github/LethalThings/LethalThings/Patches/PowerOutletStun.cs:30)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<GameNetworkManager::Start>?-723104556(GameNetworkManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<GameNetworkManager::Start>?-700195554(GameNetworkManager)
LethalThings.MonoBehaviours.GremlinEnergy.GameNetworkManager_Start (On.GameNetworkManager+orig_Start orig, GameNetworkManager self) (at O:/github/LethalThings/LethalThings/MonoBehaviours/GremlinEnergy.cs:28)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<GameNetworkManager::Start>?-1948937460(GameNetworkManager)

**Comment by apeng0907** [comment] 2024-02-23 10:57
[Info   :KawaiiBone.Remnants] Loading in items.
[Info   :KawaiiBone.Remnants] TpButton rarity: 1
[Info   :KawaiiBone.Remnants] Added TpButton as a scrap item.
[Info   :KawaiiBone.Remnants] NightVisionItem rarity: 8
[Info   :KawaiiBone.Remnants] Added NightVisionItem as a scrap item.
[Info   :KawaiiBone.Remnants] MedKitMapItem rarity: 1
[Info   :KawaiiBone.Remnants] Added MedKitMapItem as a scrap item.
[Info   :KawaiiBone.Remnants] MedKitItem rarity: 1
[Info   :KawaiiBone.Remnants] Added MedKitItem as a scrap item.
[Info   :KawaiiBone.Remnants] HelmetItem rarity: 1
[Info   :KawaiiBone.Remnants] Added HelmetItem as a scrap item.
[Info   :KawaiiBone.Remnants] StoreWheelbarrowItem rarity: 5
[Info   :KawaiiBone.Remnants] Added StoreWheelbarrowItem as a scrap item.
[Info   :KawaiiBone.Remnants] coilHead rarity: 8
[Info   :KawaiiBone.Remnants] Added coilHead as a scrap item.
[Info   :KawaiiBone.Remnants] TpButtonAdv rarity: 1
[Info   :KawaiiBone.Remnants] Added TpButtonAdv as a scrap item.
[Info   :KawaiiBone.Remnants] DivingKitItem rarity: 1
[Info   :KawaiiBone.Remnants] Added DivingKitItem as a scrap item.
[Info   :KawaiiBone.Remnants] HandheldRadar rarity: 9
[Info   :KawaiiBone.Remnants] Added HandheldRadar as a scrap item.
[Info   :KawaiiBone.Remnants] HackingTool rarity: 9
[Info   :KawaiiBone.Remnants] Added HackingTool as a scrap item.
[Info   :KawaiiBone.Remnants] RocketLauncher rarity: 9
[Info   :KawaiiBone.Remnants] Added RocketLauncher as a scrap item.
[Info   :KawaiiBone.Remnants] ToyHammer rarity: 9
[Error  :KawaiiBone.Remnants] System.ArgumentException: An item with the same key has already been added. Key: All
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000dd] in <787acc3c9a4c471ba7d971300105af24>:IL_00DD 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <787acc3c9a4c471ba7d971300105af24>:IL_0000 
  at LethalLib.Modules.Items.RegisterScrap (Item spawnableItem, System.Int32 rarity, LethalLib.Modules.Levels+LevelTypes levelFlags) [0x0002b] in <4eedb4dc36094adcb65137cf81f2803d>:IL_002B 
  at Remnants.Remnants.AddStoreItemsToScrap () [0x000a9] in <4041ce4229f34ea29ed0f7949351578e>:IL_00A9 
[Info   :KawaiiBone.Remnants] Items Are loaded in.

**Comment by Shaosil** [comment] 2024-02-28 21:21
I can't tell if this error is being caused by my mod or something in LethalThings - but either way, I'll need some more info, or perhaps a profile code to test it. If it is from my mod, it will probably only be happening because of a mod conflict.

**Comment by Rimplestilt** [comment] 2024-03-19 19:35
This is an error i am currently getting that is in red font:

[Info   :GeneralImprovements] Adding ToggleableFancyLamp behavior to FancyLamp prefab.
[Error  : Unity Log] Panel label not found.
[Error  : Unity Log] Delete file game object not found.
[Error  : Unity Log] Error occurred while refreshing save buttons: Object reference not set to an instance of an object
[Error  : Unity Log] Error occurred while updating files panel rect: Failed to find FilesPanel RectTransform.
[Error  : Unity Log] An error occurred during initialization: Object reference not set to an instance of an object

**Comment by Shaosil** [comment] 2024-04-21 15:42
I just confirmed this still happens in certain mod collections even when disabling GeneralImprovements, so it is unrelated to my info message - it just happens to come directly after it. Closing issue.

**Closed by Shaosil** 2024-04-21 15:42 UTC
