### ISSUE TITLE
Small monitors stay powerless for the host

### ISSUE THREAD

**Issue by FaithOfSin** [Shaosil/LethalCompanyMods-GeneralImprovements#184] opened 2024-05-13 13:17 UTC
Hi there!

I noticed when lightning strikes the ship and all monitors go out, the small monitors doesn´t work any more at all for the host when you turn the power back on (turn on the switch and klick the button on the big monitor).
All other players can still see them tho, it only affects the host. I couldn´t find any other solution to turn them back on, except restarting.

So I changed the option in the settings called "SyncExtraMonitorsPower" to false and now they keep being on, which is fine for me.
We tested this several times with charging metal stuff to get a lighting.

**Comment by Shaosil** [comment] 2024-05-14 05:23
I couldn't reproduce this but a lot of people reported it. I think I found the faulty code and updated it, hopefully it's fixed in v1.2.8 which is going live shortly. Ping me if it isn't though and I'll reopen this.

**Closed by Shaosil** 2024-05-14 05:23 UTC
