### ISSUE TITLE
Incompatibility with darmuhsTerminalStuff

### ISSUE THREAD

**Issue by Noranecore** [Shaosil/LethalCompanyMods-GeneralImprovements#31] opened 2024-01-16 07:18 UTC
The arrow keys to switch players on radar doesn't work well with darmuh's alwayson command which makes the terminal stay active even when you've exited it. (AdvancedCompany also has this by default) It only works the first time you go onto the terminal but when you exit the terminal and hop back on it, arrow keys no longer work unless you turn off radar view and turn it back on.

**Comment by Shaosil** [comment] 2024-01-16 13:01
Hi there,

Isn't this a duplicate of #15 you opened? I fixed it as of v1.0.16, unless I missed something or something changed of course. When I get a chance I'll test it again.

**Comment by Kayotik16** [comment] 2024-01-16 14:14
> Hi there,
> 
> Isn't this a duplicate of #15 you opened? I fixed it as of v1.0.16, unless I missed something or something changed of course. When I get a chance I'll test it again.

Can confirm incompatibility with Advanced company and darmuhsTerminalstuff
Can't see perks anymore for advanced company love the mod but I can't use it due to this issue. 
I

**Comment by Shaosil** [comment] 2024-01-16 14:18
Ok, thanks, I'll prioritize looking into this one

**Comment by Noranecore** [comment] 2024-01-16 16:52
> Hi there,
> 
> Isn't this a duplicate of #15 you opened? I fixed it as of v1.0.16, unless I missed something or something changed of course. When I get a chance I'll test it again.

I should have just replied to that issue instead, my bad. You only half-fixed the issue as the arrow keys become unusable again when exiting the terminal and getting back on it.

**Comment by Shaosil** [comment] 2024-01-16 17:00
Ah interesting, ok I'll check this out, thanks.

**Comment by Noranecore** [comment] 2024-01-17 09:07
Just an update to this issue, AdvancedCompany does not have any terminal patches anymore so this is now only an issue with the alwayson function of darmuhsTerminalStuff.

**Comment by Shaosil** [comment] 2024-01-17 16:38
> You only half-fixed the issue as the arrow keys become unusable again when exiting the terminal and getting back on it.

The arrow keys only work when the radar is active, and by default (in both base game and darmuhsTerminalStuff), the radar will close when you exit the terminal.

Unless I or the creator of darmuhsTerminalStuff adds an option to persist the radar view on returning to the terminal, I'd say this is currently functioning as intended.

**Comment by Noranecore** [comment] 2024-01-17 18:11
> > You only half-fixed the issue as the arrow keys become unusable again when exiting the terminal and getting back on it.
> 
> The arrow keys only work when the radar is active, and by default (in both base game and darmuhsTerminalStuff), the radar will close when you exit the terminal.
> 
> Unless I or the creator of darmuhsTerminalStuff adds an option to persist the radar view on returning to the terminal, I'd say this is currently functioning as intended.

darmuhsTerminalStuff does indeed have a feature to persist the radar view (its the 'alwayson' command!)

**Comment by Shaosil** [comment] 2024-01-17 19:28
Ahh it would help if I did some research first! Ok, I see the problem now, I'll see what I can do.

**Comment by Shaosil** [comment] 2024-01-17 22:17
This should be fixed as of v1.0.22 (going live shortly)

**Closed by Shaosil** 2024-01-17 22:17 UTC
