### ISSUE TITLE
Can't respawn with mod enabled.

### ISSUE THREAD

**Issue by DrKoneko** [Shaosil/LethalCompanyMods-GeneralImprovements#101] opened 2024-02-01 02:15 UTC
My friends and I were playing and we downloaded this mod. I'm not sure if it's due to another mod conflicting with this one or not but the problem is that after the ship takes off people don't respawn, and instead the game is softlocked on the ship where no one can respawn. The error from BepInEx's terminal says

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GeneralImprovements.Utilities.MonitorsHelper.ToggleExtraMonitorsPower (System.Boolean on) (at <5fc2bbd6619849179758207937ba427c>:IL_00AA)
GeneralImprovements.Patches.ManualCameraRendererPatch.SwitchScreenOn (System.Boolean on, ManualCameraRenderer __instance, System.Boolean& ___isScreenOn) (at <5fc2bbd6619849179758207937ba427c>:IL_0029)
(wrapper dynamic-method) ManualCameraRenderer.DMD<ManualCameraRenderer::SwitchScreenOn>(ManualCameraRenderer,bool)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::SwitchMapMonitorPurpose>(StartOfRound,bool)
StartOfRound+<EndOfGame>d__260.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_01E7)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)`

Disabling this mod and leaving everything else enabled results in proper behavior but missing out on all the cool features this mod provides.

**Comment by DrKoneko** [comment] 2024-02-01 02:16
Also this is what I see when I'm playing solo and have died. It just stays like this forever.

![image_2024-01-31_211539956](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/99343617/e13defd7-93b6-4cfe-a42e-6bb8c9fa7271)

**Comment by Shaosil** [comment] 2024-02-01 02:33
Something is definitely borked in the new update, trying to solve it ASAP.

**Comment by Shaosil** [comment] 2024-02-01 04:08
I added some null checks that fixed a few things, this included I believe. It's in v1.1.6, going live shortly, can you check whether it's fixed on your end when you can and I can close this? Thanks!

**Comment by MaxOhNoo** [comment] 2024-02-01 04:16
Works perfectly! Thanks!

**Comment by FlySlime** [comment] 2024-02-01 20:03
Still seems to persists in 1.1.6 for me and my friends sadly

**Comment by Shaosil** [comment] 2024-02-01 20:04
Ok, does it give you the same error or something else?

**Comment by FlySlime** [comment] 2024-02-01 22:05
> Ok, does it give you the same error or something else?

```
[Error  : Unity Log] NullReferenceException
Stack trace:
GeneralImprovements.Utilities.MonitorsHelper.ToggleExtraMonitorsPower (System.Boolean on) (at <282306f06b43469dbbaaafd8d63537fa>:IL_0058)
GeneralImprovements.Patches.ManualCameraRendererPatch.SwitchScreenOn (System.Boolean on, ManualCameraRenderer __instance, System.Boolean& ___isScreenOn) (at <282306f06b43469dbbaaafd8d6
3537fa>:IL_0029)
(wrapper dynamic-method) ManualCameraRenderer.DMD<ManualCameraRenderer::SwitchScreenOn>(ManualCameraRenderer,bool)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::SwitchMapMonitorPurpose>(StartOfRound,bool)
(wrapper dynamic-method) StartOfRound+<EndOfGame>d__260.DMD<StartOfRound+<EndOfGame>d__260::MoveNext>(StartOfRound/<EndOfGame>d__260)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)
```

**Comment by martianph** [comment] 2024-02-01 23:53
I can confirm this issue is happening still with the latest version (1.1.6).  Simply landed and launched the ship again and it never starts the next day. 

I have been testing a bit and somehow the issue doesn't happen for me when I disable the mod CorporteRestructure and keep GeneralImprovements on and vice versa. Maybe something to look at if they have incompatibilities but definitely the issue is with GeneralImprovements because CorporateRestructure as far as I know only changes the monitors. Might be a conflict with how GeneralImprovements changes the games monitors with other mods. Error below:

[Error  : Unity Log] NullReferenceException
Stack trace:
GeneralImprovements.Utilities.MonitorsHelper.ToggleExtraMonitorsPower (System.Boolean on) (at <282306f06b43469dbbaaafd8d63537fa>:IL_0058)
GeneralImprovements.Patches.ManualCameraRendererPatch.SwitchScreenOn (System.Boolean on, ManualCameraRenderer __instance, System.Boolean& ___isScreenOn) (at <282306f06b43469dbbaaafd8d63537fa>:IL_0029)
(wrapper dynamic-method) ManualCameraRenderer.DMD<ManualCameraRenderer::SwitchScreenOn>(ManualCameraRenderer,bool)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::SwitchMapMonitorPurpose>(StartOfRound,bool)
(wrapper dynamic-method) StartOfRound+<EndOfGame>d__260.DMD<StartOfRound+<EndOfGame>d__260::MoveNext>(StartOfRound/<EndOfGame>d__260)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by Shaosil** [comment] 2024-02-02 00:05
Well it always seems to be happening with the toggle monitor power function. I'm working on adding some more foolproof null checks to that, hopefully this will all be fixed in the next version.

**Comment by martianph** [comment] 2024-02-02 00:19
Yeah I did just a bit more testing and its the option "SyncExtraMonitorsPower" that is causing the issue. When that is set to false I am not getting any errors. Also I cannot seem to turn the monitors off when that is set to true.  I get the error below when pressing E on the red monitor button.

```
[Error  : Unity Log] NullReferenceException
Stack trace:
GeneralImprovements.Utilities.MonitorsHelper.ToggleExtraMonitorsPower (System.Boolean on) (at <282306f06b43469dbbaaafd8d63537fa>:IL_0058)
GeneralImprovements.Patches.ManualCameraRendererPatch.SwitchScreenOn (System.Boolean on, ManualCameraRenderer __instance, System.Boolean& ___isScreenOn) (at <282306f06b43469dbbaaafd8d63537fa>:IL_0029)
(wrapper dynamic-method) ManualCameraRenderer.DMD<ManualCameraRenderer::SwitchScreenOn>(ManualCameraRenderer,bool)
ManualCameraRenderer.SwitchScreenButton () (at <af9b1eec498a45aebd42601d6ab85015>:IL_000A)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
InteractTrigger.Interact (UnityEngine.Transform playerTransform) (at <af9b1eec498a45aebd42601d6ab85015>:IL_00AF)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Interact_performed>(GameNetcodeStuff.PlayerControllerB,UnityEngine.InputSystem.InputAction/CallbackContext)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray`1[System.Action`1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_001B)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

[Error  : Unity Log] NullReferenceException while executing 'performed' callbacks of 'Movement/Interact[/Keyboard/e]'
```

Other than this, when trying to launch with that option enabled, meaning purposefully trying to get the error, the main monitor somehow has both the moon info AND the map on it, see image below where we can see the ship in the background. So that maybe another thing to look at (or maybe it is just the symptom of the first issue)

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/18605500/07835c4f-f1c1-4e49-aec1-d6995e9db385)

**Comment by MaxOhNoo** [comment] 2024-02-02 00:54
Ignore my previous comments, still broken as of 1.1.6

**Comment by Shaosil** [comment] 2024-02-02 02:53
I believe I have this properly handled now... version v1.1.7 going live shortly, closing this for now and crossing my fingers ha

**Closed by Shaosil** 2024-02-02 02:53 UTC
