### ISSUE TITLE
[Conflict] UncertainCompany

### ISSUE THREAD

**Issue by DHStyle541** [Shaosil/LethalCompanyMods-GeneralImprovements#45] opened 2024-01-19 02:20 UTC
Hi, this is mod make conflict UncertainCompany [Feature > HideWeather ] not work
how can be not work?

On Monitor Work:
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/154591650/84face57-8cc5-4c73-8cfc-2a0edba2257e)

Terminal Moons not Work:
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/154591650/90f108c2-73f3-4ad9-98f0-8a32b337876c)

Mini Monitor Bugs:
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/154591650/27c4b53e-b203-4194-838e-808c762d994a)

Log Error:
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/154591650/375693cd-83ef-4d78-b25e-beb91694ef8d)

[LogOutput.log](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/files/13983501/LogOutput.log)

**Comment by Shaosil** [comment] 2024-01-19 02:30
Interesting, yeah I need to fix something else in that function as well. I'll have this fixed in the next release.

**Comment by DHStyle541** [comment] 2024-01-19 03:03
Ah ok i will waiting :))

And if ShowBlueMonitorBackground = false, that monitor bug like Picture on top.
can you add the Credits? like CorporateRestructure

**Comment by Shaosil** [comment] 2024-01-19 07:22
Fixed in v1.0.24, and if you set ShipTotalMonitorNum to a value other than 0, you will see the ship credits on the monitor of your choice.

**Comment by DHStyle541** [comment] 2024-01-19 16:21
@Shaosil The Weather on Terminal still showing. only Small Monitor is fixed 
i mean make the Terminal working for HideWeather ( Uncertain Company )

Small Monitor Working Fine (for BlackScreen) and Big Monitor for Weather: %!@#!@# ( working fine Uncertain Company )

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/154591650/74b4a6b2-c8dc-4b1a-80f7-cb23d6c71343)

Terminal Moons ( Not Work the Hide Weather )

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/154591650/ae48ad48-4c4a-49e3-ba61-393ad30c911c)

This mod can also hide Weather in Terminal not only in Large Monitor. please fix :) because I prefer Gacha Weather / don't know if the month is Extreme Weather or calm
UncertainCompany.cfg

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/154591650/a95554e2-405d-408b-a061-4e36e5b2217d)

**Comment by Shaosil** [comment] 2024-01-19 16:44
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/12295139/2877a3f5-3004-4537-8196-75ca8d4a5cad)
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/12295139/c77aff64-d4d3-42f9-8f11-0468f3ef7d0e)
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/12295139/83cadd3b-ae69-4a87-8cdd-a1f1683e5432)

Would you mind sharing your profile code with me? I have both Uncertain Company and my own mod enabled, and it's successfully hiding all the weather effects. There may be another mod causing an error, but I'd like to test it for myself.

**Comment by DHStyle541** [comment] 2024-01-19 17:38
Ah i know conflict. because LethalExpansionCore but Before i add (GeneralImprovements) make conflict Terminal Weather

**Comment by Shaosil** [comment] 2024-01-19 18:32
Ok, I did some testing on this. I started from scratch, and ONLY added UncertainCompany. In that case, hiding the weather works in every screen including the terminal of course.

However, as soon as I added LethalExpansionCore (and nothing else), the weather appeared in the terminal. So it can't be related to my mod since it wasn't loaded when that happened - you can reproduce this yourself if you have only UncertainCompany and LethalExpansionCore loaded.

I would guess there is something in LethalExpansionCore that is overwriting the 'moons' terminal node.

**Closed by Shaosil** 2024-01-19 18:32 UTC
