### ISSUE TITLE
Incompatible with a CrossHair MOD

### ISSUE THREAD

**Issue by smilepeak** [Shaosil/LethalCompanyMods-GeneralImprovements#85] opened 2024-01-29 03:47 UTC
https://thunderstore.io/c/lethal-company/p/CTNOriginals/CrossHair/
ShowUIReticle, whether true or false, is incompatible with CrossHair MOD, resulting in the crosshair not being displayed

**Comment by FIZL0** [comment] 2024-01-29 05:48
I also had this happen only on version 1.1.2, I'm sticking on 1.1.1 for now.

**Comment by ajsglist** [comment] 2024-01-29 18:39
To add on to this: GeneralImprovements 1.1.2 seems to break all versions of the CrossHair mod -- confirmed with the new version (1.1.0) and the older version (1.0.5)

No errors are thrown in the console

**Comment by Shaosil** [comment] 2024-01-29 20:55
I'll look into this when I can - someone said setting UseBetterMonitors = True fixes it for some reason though. Just as info for my reference.

**Comment by ajsglist** [comment] 2024-01-29 22:06
I just re-added CrossHair 1.1.0 w/ GeneralImprovements 1.1.3 for a quick check, and the CrossHair seems to be back without issues

**Comment by Shaosil** [comment] 2024-01-29 22:10
Ok good I'll go ahead and close this, thanks for verifying

**Closed by Shaosil** 2024-01-29 22:10 UTC
