### ISSUE TITLE
[BUG] Performance degradation latest update version 1.1.6

### ISSUE THREAD

**Issue by setset** [Shaosil/LethalCompanyMods-GeneralImprovements#105] opened 2024-02-01 10:28 UTC
After latest version 1.1.6 update, performance degradation happened again and even worse than the previous problem, now my fps can drop up to 30% and it happend when inside or outside ship, even after I use default configuration the problem is still there.

Sorry if I'm always nagging about performance, because not everyone has a good pc, especially my friends.

**Comment by Shaosil** [comment] 2024-02-01 13:43
You're good - Well I assume it was better in 1.1.5 because something was broke and not creating the extra monitors properly, because the only change I made in 1.1.6 is to catch an exception that prevents their creation.

One thing I would try is to make sure all the [ExtraMonitors] settings are set to default, as well as FixPersonalScanner.

Then test your FPS, and if it's fine, that means something about the extra monitors is causing the lag - you can try to slowly change the monitor settings back to what you had and see what in particular is causing the drop. The only thing I can think of that might cause performance issues in there is changing something about the internal and external cams - if they are left at 0 FPS (unlimited - vanilly) and 1 upscaling (vanilla), that should be the same behavior as base game.

**Comment by smilepeak** [comment] 2024-02-02 07:00
I also encountered the same problem
FPS has dropped significantly！！

**Comment by setset** [comment] 2024-02-03 07:00
Sorry for the late reply, just got around to playing again.

I've tried every setting, turning every setting off and on but nothing seems to work, even with the latest update.

**Comment by Shaosil** [comment] 2024-02-04 01:53
Sorry for all the back and forth, this is a really difficult one to diagnose on my machine - when testing it personally, I only get about 10 FPS drops with my mod, and many others report the same on the modding discord. There are a select few however that seem to experience the drops more than others.

And just to double confirm, with the identical configuration and monitor settings all at defaults, you get a huge FPS drop WITH my mod as opposed to the same settings and mods EXCEPT mine?

Perhaps you could pass me your profile code?

**Comment by Shaosil** [comment] 2024-02-06 22:25
I made one small change related to performance in upcoming v1.1.8, hopefully it helps. Still having trouble narrowing down the exact cause though.

**Comment by Shaosil** [comment] 2024-02-11 00:30
I believe this may be fixed in v1.1.8 actually - many people reported the main issue was fixed after updating. It seems to have been caused by an accidental search for a component every frame that I was doing. Closing for now.

**Closed by Shaosil** 2024-02-11 00:30 UTC
