### ISSUE TITLE
[Suggestion] Toggle for Teleports and/or keep items 

### ISSUE THREAD

**Issue by GamerKarl** [Shaosil/LethalCompanyMods-GeneralImprovements#76] opened 2024-01-26 16:29 UTC
What I mean by the title is a little true or false to use or not the general improvements teleport settings so another mod can take over 

OR

adding a space to choose what items to keep when teleporting for the individual items so that the host can decide what to keep when teleporting or inverse teleporting.

this issue came to me when I tried to use BetterTeleporter from SirTyler, General Improvements overrides that mod and can't make it so that the teleporter can keep items and resorted to another one in which I can't choose what items to keep for the individual teleports

**Comment by Shaosil** [comment] 2024-01-26 17:46
Sure, I have this on my backlog actually. This is a duplicate of #20 so I'll close this one to keep track of it in one piece. Thanks!

**Closed by Shaosil** 2024-01-26 17:46 UTC

**Comment by Shaosil** [comment] 2024-02-29 20:54
Added "NonScrap" as an option to keep for both teleporters in v1.1.10, going live soon.
