### ISSUE TITLE
[Incompatibility] Touchscreen's hitbox shifts to be between two monitors

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#78] opened 2024-01-27 06:05 UTC
When you have [Touchscreen](https://github.com/TheDeadSnake/LC-Touchscreen) and GeneralImprovements mods installed, if you set `UseBetterMonitors = true` in the config, [Touchscreen's](https://github.com/TheDeadSnake/LC-Touchscreen) monitor hitbox shifts to be between two monitors instead of aligning perfectly with the center monitor.
![Lethal_Company_86ijdx8PdF](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/a526f5e4-5c0a-42f8-957a-8047ba527fde)

**Comment by CommanderSlav** [comment] 2024-01-29 19:05
I've submitted a report on the touchscreen mod github also. 

Further details, because of the shift of the screen, with how the touch screen mod works, it prevents you from clicking the "change" button unless you get up on the console and crouch while looking at it. 

Very easily reproducible.

**Comment by NilaierMusic** [comment] 2024-01-29 20:59
> I've submitted a report on the touchscreen mod github also.
> 
> Further details, because of the shift of the screen, with how the touch screen mod works, it prevents you from clicking the "change" button unless you get up on the console and crouch while looking at it.
> 
> Very easily reproducible.

Added a reproduction guide to showcase this bug on [Touchscreen's issue,](https://github.com/TheDeadSnake/LC-Touchscreen/issues/18#issuecomment-1915552705) so both devs figure out what we're talking about.

**Comment by TheDeadSnake** [comment] 2024-01-29 22:53
Fixed in TouchScreen v1.0.10, this issue can be closed.

**Comment by Shaosil** [comment] 2024-01-29 23:05
Excellent, thanks for the update!

**Closed by Shaosil** 2024-01-29 23:05 UTC
