### ISSUE TITLE
TooManySuits suits on other pages don't load correctly

### ISSUE THREAD

**Issue by MagicCraftMaster** [Shaosil/LethalCompanyMods-GeneralImprovements#173] opened 2024-05-08 00:17 UTC
In the latest update (1.2.5) any suits not on page one fail to load unless you are the one to wear it then it works properly.
Downgrading to 1.2.4 doesn't cause this issue

**Comment by Shaosil** [comment] 2024-05-08 13:28
Hi, could you give me a profile code? I tried reproducing this but all the suit pages load for me even in a new save.

**Comment by Shaosil** [comment] 2024-05-08 21:51
Awesome thanks I'll look into it

**Comment by Shaosil** [comment] 2024-05-09 13:25
@MagicCraftMaster Actually I just tested without GI and that appears to be a bug with TooManySuits. Specifically, if a player (for example the host) has NOT changed suit pages yet, the suit game objects have not been loaded in for them. Then if someone else (for example the client) changes suit pages and selects a suit, the host will not see that suit, assumedly because they haven't loaded it yet.

If I change pages first however, allowing the suits to load in, I can see the client change their suit as expected.

It may have happened to work on GI v1.2.4 because you loaded the suit pages first. But I'll leave this issue open until you confirm.

**Comment by Shaosil** [comment] 2024-05-14 12:29
Closing under the assumption my last message is correct. If not, feel free to ping me for the grand reopening :)

**Closed by Shaosil** 2024-05-14 12:29 UTC
